objects
h1alexbel/js pull request #19
Opened 2023-08-07 14:31 UTC by h1alexbel

closes #18

2023-08-08 11:48 UTC, suprugafad requested changes

2023-08-08 11:48 UTC, suprugafad commented on src/04-objects/src/immutable.js
> +      Object.defineProperty(immu, field, {
it's better also to define configurable: false here

2023-08-08 12:40 UTC, h1alexbel commented
@suprugafad fixed, take a look please again

2023-08-08 13:08 UTC, suprugafad approved these changes

2023-08-17 14:04 UTC, h1alexbel commented
@rultor merge

2023-08-17 14:07 UTC, rultor commented
> @rultor merge

@h1alexbel Oops, I failed. You can see the full log [here](https://www.rultor.com/t/34273-1682349266) (spent 14s)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 665953
+ echo '1.75.1 50eb0c708'
1.75.1 50eb0c708
+ date
Thu 17 Aug 2023 04:06:58 PM CEST
+ uptime
 16:06:58 up 266 days, 20:45,  0 users,  load average: 0.02, 0.01, 0.04
+ cat
com.rultor.spi.Profile: There is no 'merge' section in .rultor.yml for branch master in repo h1alexbel/js
	at com.rultor.agents.req.StartsRequest.docker(StartsRequest.java:350)
	at com.rultor.agents.req.StartsRequest.vars(StartsRequest.java:255)
	at com.rultor.agents.req.StartsRequest.script(StartsRequest.java:148)
	at com.rultor.agents.req.StartsRequest.process(StartsRequest.java:109)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:75)
	at com.rultor.spi.Agent.execute(Agent.java:84)
	at com.rultor.agents.VerboseAgent.execute(VerboseAgent.java:62)
	at com.rultor.Routine.process(Routine.java:202)
	at com.rultor.Routine.unsafe_aroundBody0(Routine.java:180)
	at com.rultor.Routine.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.unsafe(Routine.java:175)
	at com.rultor.Routine.run(Routine.java:142)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler.lambda./run.sh(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)

+ exit -1
'cid' file is absent, most probably the Docker container wasn't started correctly
```

2023-08-17 14:08 UTC, merged